# NUMPY FUNDAMENTALS

In [109]:
#NUMPY AND N-D ARRAYS
import numpy as np

In [110]:
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [111]:
type(arr1)

numpy.ndarray

In [112]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

arr3=np.zeros((2,3))
arr3
#SIMILARLY WE CAN DO FOR ONES


array([[0., 0., 0.],
       [0., 0., 0.]])

In [113]:
#IDENTITY MATRIX // DIAGONALLY ALL VALUES ARE 1 REMAINING ARE ZERO
arr5=np.identity(5)
arr5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
arr6=np.arange(10)  # a range similarly like range
print(arr6) 
arr7=np.arange(5,10)   # soruce and final destination
print(arr7)
arr8=np.arange(5,10,2)   # soruce and final destination leaving 2 numbers
print(arr8)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[5 7 9]


In [115]:
# linspace function does linearly spacing 
arr9=np.linspace(5,20,3)
print(arr9) 

arr10=arr8.copy()
print(arr10)

[ 5.  12.5 20. ]
[5 7 9]


In [116]:
arr1

array([1, 2, 3, 4])

In [117]:
arr1.ndim  # gives us the dimensions of the array

1

In [118]:
arr1.dtype

dtype('int32')

In [119]:
arr9.dtype

dtype('float64')

In [120]:
#converts to any data type
arr9.astype('int')

array([ 5, 12, 20])

In [121]:

lista=range(100)
arr11=np.arange(100)


In [122]:
import sys

In [123]:
print(sys.getsizeof(87)*len(lista))
print(arr11.itemsize*arr11.size)


2800
400


## NUMPY ARRAYS VS LISTS
### CALCULATING TIME REQUIRED FOR np.arrays & regular lists

In [124]:
import time

x=range(100000000)
y=range(100000000,200000000)
start_time=time.time()

c=[x+y for x,y in zip(x,y)]
print(time.time()-start_time)


#---------------------------------------------------
a=np.arange(100000000)
b=np.arange(100000000,200000000)
start_time=time.time()
c=a+b 

print(time.time()-start_time)

17.41089916229248
10.46317195892334


# INDEXING SLICING AND ITERATION

In [125]:
arr12=np.arange(24).reshape(6,4)     # vertical 6 rows and 4 columns...we can reshape the given desired array on the basis of their multiples


print(arr12)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [126]:
new=arr12[2]
print(new)
# here we have obtained the 3rd columnn
new1=arr12[:,2]  #colon chya adhi kahi nasel tr it considers as all elements present in the data 
print(new1)

[ 8  9 10 11]
[ 2  6 10 14 18 22]


In [127]:
qw=arr12[:,2]
print(qw)
print("\n")
we=arr12[2:4,1:3]   #FIRST ROWS THEN COLOUMN  
print(we)

[ 2  6 10 14 18 22]


[[ 9 10]
 [13 14]]


# ITERATIONS
#### USED A 'FOR' LOOP

In [128]:

# IF WE WANT TO PUT ANY PARTICULAR FILTER TO ANY IMAGE WE CAN USE nditer
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## MATHEMATICAL OPERATIONS

In [129]:
arr13=np.array([1,2,3,4])
arr14=np.array([5,6,7,8])



In [130]:
arr14-arr13

array([4, 4, 4, 4])

In [131]:
arr14*arr13

array([ 5, 12, 21, 32])

In [132]:
arr14>10

array([False, False, False, False])

In [133]:
arr14+arr13

array([ 6,  8, 10, 12])

### DOT PRODUCT
#### HAVING MENTIONED THE SIZE IS SAME OF BOTH THE MATRIX

In [134]:
arr15=np.arange(6).reshape(3,2)
print(arr15)
print("\n")
arr16=np.arange(6,12).reshape(2,3)
print(arr16)
print("\n")
arr17=arr15.dot(arr16)
print(arr17)


[[0 1]
 [2 3]
 [4 5]]


[[ 6  7  8]
 [ 9 10 11]]


[[ 9 10 11]
 [39 44 49]
 [69 78 87]]


In [135]:
arr14.max()    

arr15.min()

0

##### DEFINE AXIS OF PARTICULAR MATRIX TO GET IT'S MIN,MAX

In [136]:
arr18=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr18)

arr18.min(axis=0)

arr18.max(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 6, 9])

### IMPPORTANT FUNCTIONS IN NUMPY

In [137]:
arr18.mean()

5.0

In [138]:
arr18.mean(axis=0)

array([4., 5., 6.])

In [139]:
arr18.std()

2.581988897471611

In [140]:
np.median(arr18)

5.0

In [141]:
np.exp(arr18)   # exponent of arr18

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### SIN functions

In [142]:
np.sin(arr18)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

# RESHAPING NUMPY ARRAYS

In [143]:
# provides the dimension
arr18.ndim

2

#### RAVEL FUNCTION CAN CONVERT ANY DIMENSION ARRAY TO 1 DIMENSION ARRAY

In [144]:
arr18.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### RESHAPE IS TO CONVERT ANY ARRAY SAY OF SIZE 24 IN ANY FORMAT SUCH AS [6,4] ,[12,2] ETC

In [146]:
arr18.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

#### TRANSPOSE:- ROWS TO COLUMNS ,COLUMNS TO ROWS

In [147]:
arr18.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### hstack does HORIZONTAL STACKING OF PROVIDED ARRAYS
#### vstack does VERTICAL STACKING OF PROVIDED ARRAYS

In [155]:
zx=np.array([1,2,3,4])
cx=np.array([4,5,6,8])
yu=np.hstack((zx,cx))
print(yu)
op=np.vstack((zx,cx))
print(op)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


#### SPLITING
##### WE CAN SPLIT THE ARRAY IN EQUAL PARTS

In [159]:
np.hsplit(zx,1)

[array([1, 2, 3])]

In [167]:
np.split(zx,1)

[array([1, 2, 3])]

## FANCY INDEXING

In [168]:
arr19=np.arange(24).reshape(6,4)
arr19

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [177]:
y=arr19[:,[0,2]]  # ACCESSING COLUMNS DIRECTLY USING FANCY INDEXES
print(y)
print("\n")
z=arr19[[1,2,3]]  # ACCESSING ROWS DIRECTLY USING FANCY INDEXES
print(z)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## INDEXING USING BOOLEAN ARRAYS

In [178]:
arr20=np.random.randint(low=1,high=50,size=10).reshape(5,2)
arr20

array([[21, 47],
       [48, 45],
       [14, 35],
       [43, 23],
       [40, 17]])

In [181]:
arr20[arr20>30]   # here we achieved indexing through boolean arrays

array([47, 48, 45, 35, 43, 40])

In [180]:
arr20>30

array([[False,  True],
       [ True,  True],
       [False,  True],
       [ True, False],
       [ True, False]])